version: "3.3"

services: 
    jenkins:
        image: jenkins-docker
        build: ./docker/jenkins
        volumes:
            - ./jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        ports: 
            - 8080:8080
